flowchart TD
    subgraph DP["Data Preprocessing"]
        BS[Background subtraction] --> 
        WO["Denoise via undecimated wavelet transformation"] -->
        WC["Apply wavelength calibration"] -->
        CER["Continuum removal"] -->|"Reduced Data Record (RDR)"| IRF["Apply Instrumental Response Function (IRF)"]
    end

    db[(LIBS Data)] -->|"Experimental data record (EDR)"| DP

    DP -->|"Cleaned, calibrated spectra (CCS)"| C

    subgraph C["Calibration"]
        Input --> NOSM["`Normalize
        (Norm 1 or Norm 3)`"] --> F
        F[Full Model] --> |"Initial Estimate"| H[Submodel Selection]
        
        SM["Submodel (Low, Mid, High)"]
        BR["`Overlap range of submodels
        (Low-Mid; Mid-High)`"]

        H -.->|In submodel range| SM
        H -.-|Within overlap range| BR

        BR --> BO["`Blend
        (*Linear weighted sum*)`"]

        SM -->|Model output| J
        BO -->|Blended output| J

        Input --> WE["Weigh by inverse IRF"] --> NOI["`Normalize
        (Norm 1 or Norm 3)`"] --> I


        
        I["`ICA with Joint Approximate Diagonalization of Eigenmatrices (JADE)`"]
        I -->|Components & Mixing matrix| J


        J["`Combine PLS & ICA
        (_weigted average_)`"]
    end
    
    C --> K["Multivariate Oxide Composition (MOC) Derivation"]
